
import React from "react";
import { Question } from "./types";
import { 
  CheckCircle, AlertCircle, FileText, User, 
  Home, Phone, Heart, UserPlus, Shield, BookText,
  Pill, CalendarClock, UserCircle
} from "lucide-react";

// Main sections/questions
export const questions: Question[] = [
  {
    id: "personal",
    titleEn: "Personal Information",
    titleEs: "Información Personal",
    descriptionEn: "Basic personal details",
    descriptionEs: "Datos personales básicos",
    icon: <User className="h-5 w-5" />,
    subQuestions: [
      {
        id: "fullName",
        questionEn: "Full Name",
        questionEs: "Nombre Completo",
        type: "text",
        required: true,
      },
      {
        id: "dob",
        questionEn: "Date of Birth",
        questionEs: "Fecha de Nacimiento",
        type: "text",
        required: true,
      },
      {
        id: "nie",
        questionEn: "NIE Number (Spanish Foreigner ID)",
        questionEs: "Número NIE (Identificación de Extranjero)",
        type: "text",
        required: true,
      },
      {
        id: "passport",
        questionEn: "Passport Number",
        questionEs: "Número de Pasaporte",
        type: "text",
        required: true,
      },
      {
        id: "email",
        questionEn: "Email Address",
        questionEs: "Correo Electrónico",
        type: "email",
        required: true,
      },
    ],
  },
  {
    id: "address",
    titleEn: "Primary Address",
    titleEs: "Dirección Principal",
    descriptionEn: "Your home address information",
    descriptionEs: "Información de su domicilio",
    icon: <Home className="h-5 w-5" />,
    subQuestions: [
      {
        id: "street",
        questionEn: "Street Address",
        questionEs: "Dirección",
        type: "text",
        required: true,
      },
      {
        id: "city",
        questionEn: "City",
        questionEs: "Ciudad",
        type: "text",
        required: true,
      },
      {
        id: "province",
        questionEn: "Province",
        questionEs: "Provincia",
        type: "text",
        required: true,
      },
      {
        id: "postalCode",
        questionEn: "Postal Code",
        questionEs: "Código Postal",
        type: "text",
        required: true,
      },
    ],
  },
  {
    id: "postalAddress",
    titleEn: "Postal Address (if different)",
    titleEs: "Dirección Postal (si es diferente)",
    descriptionEn: "Your alternative mailing address",
    descriptionEs: "Su dirección postal alternativa",
    icon: <Home className="h-5 w-5" />,
    subQuestions: [
      {
        id: "sameAsHome",
        questionEn: "Same as Home Address?",
        questionEs: "¿Igual que la Dirección Principal?",
        type: "boolean",
        required: true,
      },
      {
        id: "postalStreet",
        questionEn: "Street Address",
        questionEs: "Dirección",
        type: "text",
      },
      {
        id: "postalCity",
        questionEn: "City",
        questionEs: "Ciudad",
        type: "text",
      },
      {
        id: "postalProvince",
        questionEn: "Province",
        questionEs: "Provincia",
        type: "text",
      },
      {
        id: "postalCode",
        questionEn: "Postal Code",
        questionEs: "Código Postal",
        type: "text",
      },
    ],
  },
  {
    id: "phoneNumbers",
    titleEn: "Phone Numbers",
    titleEs: "Números de Teléfono",
    descriptionEn: "Your contact phone numbers",
    descriptionEs: "Sus números de teléfono de contacto",
    icon: <Phone className="h-5 w-5" />,
    subQuestions: [
      {
        id: "mobilePhone",
        questionEn: "Mobile Phone",
        questionEs: "Teléfono Móvil",
        type: "phone",
        required: true,
      },
      {
        id: "homePhone",
        questionEn: "Home Phone",
        questionEs: "Teléfono Fijo",
        type: "phone",
      },
    ],
    allowMultiple: true,
  },
  {
    id: "emergencyContacts",
    titleEn: "Emergency Contacts",
    titleEs: "Contactos de Emergencia",
    descriptionEn: "People to contact in case of emergency",
    descriptionEs: "Personas a contactar en caso de emergencia",
    icon: <UserPlus className="h-5 w-5" />,
    subQuestions: [
      {
        id: "contactName",
        questionEn: "Contact Name",
        questionEs: "Nombre del Contacto",
        type: "text",
        required: true,
      },
      {
        id: "relationship",
        questionEn: "Relationship",
        questionEs: "Relación",
        type: "text",
        required: true,
      },
      {
        id: "contactPhone",
        questionEn: "Phone Number",
        questionEs: "Número de Teléfono",
        type: "phone",
        required: true,
      },
      {
        id: "alternatePhone",
        questionEn: "Alternate Phone",
        questionEs: "Teléfono Alternativo",
        type: "phone",
      },
      {
        id: "contactEmail",
        questionEn: "Email",
        questionEs: "Correo Electrónico",
        type: "email",
      },
    ],
    allowMultiple: true,
  },
  {
    id: "allergies",
    titleEn: "Allergies",
    titleEs: "Alergias",
    descriptionEn: "Information about your allergies",
    descriptionEs: "Información sobre sus alergias",
    icon: <AlertCircle className="h-5 w-5" />,
    subQuestions: [
      {
        id: "hasAllergies",
        questionEn: "Do you have any allergies?",
        questionEs: "¿Tiene alguna alergia?",
        type: "boolean",
        required: true,
      },
      {
        id: "allergyDetails",
        questionEn: "Please list your allergies and reactions",
        questionEs: "Por favor, liste sus alergias y reacciones",
        type: "textarea",
      },
    ],
  },
  {
    id: "medicalConditions",
    titleEn: "Medical Conditions",
    titleEs: "Condiciones Médicas",
    descriptionEn: "Information about your health conditions",
    descriptionEs: "Información sobre sus condiciones de salud",
    icon: <Heart className="h-5 w-5" />,
    subQuestions: [
      {
        id: "hasMedicalConditions",
        questionEn: "Do you have any medical conditions?",
        questionEs: "¿Tiene alguna condición médica?",
        type: "boolean",
        required: true,
      },
      {
        id: "conditionDetails",
        questionEn: "Please describe your medical conditions",
        questionEs: "Por favor, describa sus condiciones médicas",
        type: "textarea",
      },
    ],
  },
  {
    id: "medications",
    titleEn: "Current Medications",
    titleEs: "Medicamentos Actuales",
    descriptionEn: "Medications you are currently taking",
    descriptionEs: "Medicamentos que está tomando actualmente",
    icon: <Pill className="h-5 w-5" />,
    subQuestions: [
      {
        id: "medicationName",
        questionEn: "Medication Name",
        questionEs: "Nombre del Medicamento",
        type: "text",
        required: true,
      },
      {
        id: "dosage",
        questionEn: "Dosage",
        questionEs: "Dosis",
        type: "text",
        required: true,
      },
      {
        id: "frequency",
        questionEn: "Frequency",
        questionEs: "Frecuencia",
        type: "text",
        required: true,
      },
      {
        id: "purpose",
        questionEn: "Purpose",
        questionEs: "Propósito",
        type: "text",
      },
    ],
    allowMultiple: true,
  },
  {
    id: "doctorInformation",
    titleEn: "Doctor Information",
    titleEs: "Información del Médico",
    descriptionEn: "Your primary healthcare providers",
    descriptionEs: "Sus proveedores de atención médica primaria",
    icon: <UserCircle className="h-5 w-5" />,
    subQuestions: [
      {
        id: "doctorName",
        questionEn: "Doctor's Name",
        questionEs: "Nombre del Médico",
        type: "text",
        required: true,
      },
      {
        id: "doctorSpecialty",
        questionEn: "Specialty",
        questionEs: "Especialidad",
        type: "text",
      },
      {
        id: "doctorPhone",
        questionEn: "Doctor's Phone",
        questionEs: "Teléfono del Médico",
        type: "phone",
        required: true,
      },
      {
        id: "doctorAddress",
        questionEn: "Doctor's Address/Clinic Name",
        questionEs: "Dirección del Médico/Nombre de la Clínica",
        type: "text",
      },
    ],
    allowMultiple: true,
  },
  {
    id: "additionalInfo",
    titleEn: "Additional Information",
    titleEs: "Información Adicional",
    descriptionEn: "Any other information you'd like to provide",
    descriptionEs: "Cualquier otra información que desee proporcionar",
    icon: <FileText className="h-5 w-5" />,
    subQuestions: [
      {
        id: "preferredHospital",
        questionEn: "Preferred Hospital",
        questionEs: "Hospital Preferido",
        type: "text",
      },
      {
        id: "bloodType",
        questionEn: "Blood Type",
        questionEs: "Tipo de Sangre",
        type: "select",
        options: [
          { id: "aPositive", textEn: "A+", textEs: "A+", value: "A+" },
          { id: "aNegative", textEn: "A-", textEs: "A-", value: "A-" },
          { id: "bPositive", textEn: "B+", textEs: "B+", value: "B+" },
          { id: "bNegative", textEn: "B-", textEs: "B-", value: "B-" },
          { id: "abPositive", textEn: "AB+", textEs: "AB+", value: "AB+" },
          { id: "abNegative", textEn: "AB-", textEs: "AB-", value: "AB-" },
          { id: "oPositive", textEn: "O+", textEs: "O+", value: "O+" },
          { id: "oNegative", textEn: "O-", textEs: "O-", value: "O-" },
          { id: "unknown", textEn: "Unknown", textEs: "Desconocido", value: "unknown" },
        ],
      },
      {
        id: "additionalNotes",
        questionEn: "Additional Notes or Special Instructions",
        questionEs: "Notas Adicionales o Instrucciones Especiales",
        type: "textarea",
      },
    ],
  },
];
