
export const paymentContent = {
  en: {
    title: "Payment Method",
    description: "Select how you would like to pay",
    creditCard: "Credit Card",
    paypal: "PayPal",
    bankTransfer: "Bank Transfer",
    cardDetails: "Card Details",
    cardNumber: "Card Number",
    cardholderName: "Cardholder Name",
    expiryDate: "Expiry Date",
    cvc: "CVC",
    mmyy: "MM/YY",
    secure: "Secured with 256-bit encryption",
    cardInfo: "We accept Visa, Mastercard, and American Express",
    continueToPaypal: "Continue to PayPal",
    securedByPaypal: "Secured by PayPal",
    bankTransferDetails: "Bank Transfer Details",
    bankTransferReference: "Reference",
    bankTransferNote: "Please include the reference number in your transfer. Payments typically process within 1-3 business days.",
    paypalBenefits: "PayPal Benefits",
    paypalFast: "Fast and secure checkout process",
    paypalNoCardDetails: "No need to enter your card details on our site",
    paypalProtection: "Purchase protection for eligible items"
  },
  es: {
    title: "Método de Pago",
    description: "Seleccione cómo desea pagar",
    creditCard: "Tarjeta de Crédito",
    paypal: "PayPal",
    bankTransfer: "Transferencia Bancaria",
    cardDetails: "Detalles de la Tarjeta",
    cardNumber: "Número de Tarjeta",
    cardholderName: "Nombre del Titular",
    expiryDate: "Fecha de Caducidad",
    cvc: "CVC",
    mmyy: "MM/AA",
    secure: "Protegido con encriptación de 256 bits",
    cardInfo: "Aceptamos Visa, Mastercard y American Express",
    continueToPaypal: "Continuar a PayPal",
    securedByPaypal: "Protegido por PayPal",
    bankTransferDetails: "Detalles de Transferencia Bancaria",
    bankTransferReference: "Referencia",
    bankTransferNote: "Por favor incluya el número de referencia en su transferencia. Los pagos generalmente se procesan dentro de 1-3 días hábiles.",
    paypalBenefits: "Beneficios de PayPal",
    paypalFast: "Proceso de pago rápido y seguro",
    paypalNoCardDetails: "No es necesario ingresar los datos de su tarjeta en nuestro sitio",
    paypalProtection: "Protección de compra para artículos elegibles"
  }
};
